### ISSUE TITLE
IE是如何兼容的？

### ISSUE THREAD

**Issue by Jvaeyhcd** [anjoy8/Nuxt.tBug#1]
大神，请问您是如何兼容IE浏览器的，我的Nuxt.js项目在IE上各种问题，报SCRIPT1003的错误。

**Comment by anjoy8** [comment]
你好，我测试了下，我的项目是兼容 IE 9(+) 的，
我不知道你的浏览器版本是多少？
其实我也没有做什么兼容处理，Nuxt 官方的就是这样

**Comment by anjoy8** [comment]
你可以在 IE 浏览器里测试测试多个版本

**Comment by Jvaeyhcd** [comment]
@anjoy8 没有问题了，我解决了在nuxt.js中引入：
``` js
...
module.exports = {
  mode: 'universal',

  /*
   ** Headers of the page
   */
  head: {
    ...
    script: [
      { src: 'https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/7.2.5/polyfill.min.js' }
    ],
    ...
  },
  ...
  /*
   ** Build configuration
   */
  build: {
    // 为 JS 和 Vue 文件定制 babel 配置 -> https://nuxtjs.org/api/configuration-build/#analyze
    babel: {
      presets({ isServer }) {
        return [
          [
            require.resolve('@nuxtjs/babel-preset-app'),
            {
              targets: isServer
                ? { node: '10.4.0' }
                : { ie: 9 } 
            }
          ]
        ]
      }
    },
    ...
  }
}
```

**Comment by anjoy8** [comment]
真棒的

**Comment by conquer123** [comment]
> @anjoy8 没有问题了，我解决了，在nuxt.js中引入：
> 
> ```js
> ...
> module.exports = {
>   mode: 'universal',
> 
>   /*
>    ** Headers of the page
>    */
>   head: {
>     ...
>     script: [
>       { src: 'https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/7.2.5/polyfill.min.js' }
>     ],
>     ...
>   },
>   ...
>   /*
>    ** Build configuration
>    */
>   build: {
>     // 为 JS 和 Vue 文件定制 babel 配置 -> https://nuxtjs.org/api/configuration-build/#analyze
>     babel: {
>       presets({ isServer }) {
>         return [
>           [
>             require.resolve('@nuxtjs/babel-preset-app'),
>             {
>               targets: isServer
>                 ? { node: '10.4.0' }
>                 : { ie: 9 } 
>             }
>           ]
>         ]
>       }
>     },
>     ...
>   }
> }
> ```
> 
> 通过如上的配置后，我的IE就能够正常打开了。

请问大神，我按照你这个方法在IE下还是打不开，报错：
polyfill-eventsource added missing EventSource to window 
SCRIPT1002: 语法错误 
vendors.app.js, 行558 字符1

**Comment by yinzhenkun** [comment]
适配低版本IE   编译完的js文件 把use strict 全替换"" 亲测可用
